title: "My security blog"
description: "Projects and posts on data security"
theme: jekyll-theme-cayman-blog
header:
  title: "My security blog"
nav:
  - title: "Inicio"
    url: /
  - title: "Proyectos"
    url: /projects

